### ISSUE TITLE
Error while importing "KernelConv2D"

### ISSUE THREAD

**Issue by lizijue** [xufangchn/GLF-CR#1]
Hi,

I wanna run the file "net_CR_RDN.py" now, but get a exception shown in the figure below:

![QQ截图20220920201439](https://user-images.githubusercontent.com/45393123/191255731-47e0b6f3-866a-43ee-89f7-a78b524255bf.png)

I follow your modification steps in "https://github.com/xufangchn/GLF-CR/blob/main/codes/FAC/README.md", but find it useless for this exception. 

I am not familliar with using C language in Python files, so could you please help me to find out the cause?

I would very appreciate if you could help me.

**Comment by ooolike** [comment]
I met the same question:-)

**Comment by xufangchn** [comment]
Sorry for the late reply. I have updated the 'Prerequisites & Installation' in README.md. You can follow the steps to build the environment. If you use  NVIDIA Geforce RTX 3090 GPUs where CUDA 11.0+ is supported, you can use the "kernel2d_conv" in "submodules.py".

**Comment by bianjiaming** [comment]
Thank you for your explanation. I would like to know more about how to use the 'kernel2d_conv' function in 'submodules.py'. Could you provide detailed instructions on how to use it? Thank you in advance!

**Comment by SpectorSong** [comment]
> Thank you for your explanation. I would like to know more about how to use the 'kernel2d_conv' function in 'submodules.py'. Could you provide detailed instructions on how to use it? Thank you in advance!

I found the source code here: https://zhuanlan.zhihu.com/p/77718601
